---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars_files:
    - vars/main.yml
  roles:
    - development
    - server
    - postgresql
    - redis
    - supervisor
  tasks:
  - name: check if tinybee DB already existing
    become_user: postgres
    shell: "psql -lqt | cut -d \\| -f 1 | grep -w tinybee"
    register: tinybee_db_exists
    changed_when: False
    failed_when: not (tinybee_db_exists.rc == 0 or tinybee_db_exists.rc == 1)

  - name: populate tinybee DB
    become_user: "{{tinybee_user}}"
    command: "python cli.py db_create"
    args:
      chdir: "{{vagrant_dir}}"
    when: tinybee_db_exists.rc != 0
